### ISSUE TITLE
a note

### ISSUE THREAD

**Issue by mkhabibullin** [tele-traan/testbaza#2]
Привет =)
похоже этот код используется только для того,  чтобы достать айди сохраненного объекта
https://github.com/tele-traan/testbaza/blob/fede62485ae795d9656a38c8a98ae21a26e0aefd/Repositories/Questions/QuestionsRepository.cs#L53-L57

но насамом деле, answer уже должен содержать нужный тебе айди, т.к. после того как ты его сохраняешь тут
https://github.com/tele-traan/testbaza/blob/master/Repositories/Questions/QuestionsRepository.cs#L50
answer-у присвоится айди из БД

**Comment by mkhabibullin** [comment]
код посмотрел, хорошо пишешь, молодец =)
скайп - khabibullin.m.m
можем как-нибудь что-то на подобие презентации проекта устроить, по скайпу
идеи могу подкинуть, ну и на вопросы, если есть, могу ответить

**Comment by tele-traan** [comment]
> но насамом деле, answer уже должен содержать нужный тебе айди, т.к. после того как ты его сохраняешь тут https://github.com/tele-traan/testbaza/blob/master/Repositories/Questions/QuestionsRepository.cs#L50 answer-у присвоится айди из БД

Аа, не знал, что так работает. То есть получается этой переменной Answer автоматически после SaveChangesAsync присваивается ссылка именно на сущность из базы, или просто полям первичных и внешних ключей присваиваются значения?

**Comment by mkhabibullin** [comment]
Ага, айди сущности будет проставлен, ну и да, если есть связи, то эти связи
тоже пролинкуются, т.е. если есть например связь one-to-many, то у дочерних
сущностей тоже проставится корректный айди для парент сущности

пт, 1 апр. 2022 г., 23:00 Timur ***@***.***>:
